name: Buscador Diario Oposiciones

on:
  schedule:
    - cron: '0 8 * * 1-6'  # Se ejecuta a las 8:00 AM de Lunes a S치bado (Excluye Domingos)
  workflow_dispatch:        # Permite ejecuci칩n manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el c칩digo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librer칤as
        run: pip install requests beautifulsoup4 python-docx

      - name: Ejecutar buscador
        run: python buscador.py

      - name: Enviar por Email (GMAIL)
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "游늭 Reporte Semanal Oposiciones TIC"
          to: ${{ secrets.EMAIL_USER }}
          from: "Buscador Autom치tico"
          body: "Se adjunta el informe de los 칰ltimos 7 d칤as. (Ejecuci칩n autom치tica de Lunes a S치bado)."
          attachments: "*.docx"
