name: Buscador Diario Oposiciones

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el c√≥digo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librer√≠as
        run: pip install requests beautifulsoup4 python-docx

      - name: Ejecutar buscador
        run: python buscador.py

      - name: Enviar por Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          # Servidor espec√≠fico de Outlook para evitar timeouts
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "üìÇ Reporte Oposiciones"
          to: ${{ secrets.EMAIL_USER }}
          from: "Buscador Autom√°tico"
          body: "Informe de oposiciones adjunto."
          attachments: "*.docx"
          # Esta l√≠nea es clave para el puerto 587
          secure: false
