name: Buscador Diario Oposiciones

on:
  schedule:
    - cron: '0 8 * * *'  # Esto se ejecuta a las 8:00 AM todos los días
  workflow_dispatch:      # Esto te permite darle a un botón y ejecutarlo cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python en el servidor
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar las librerías necesarias
        run: |
          pip install requests beautifulsoup4 python-docx

      - name: Ejecutar el buscador
        run: python buscador.py

      - name: Guardar el Word generado como resultado
        uses: actions/upload-artifact@v4
        with:
          name: Informe-Oposiciones
          path: "*.docx"
