name: Buscador Diario Oposiciones

on:
  schedule:
    - cron: '0 8 * * *'  # Se ejecuta a las 8:00 AM cada d铆a
  workflow_dispatch:      # Permite ejecuci贸n manual con el bot贸n "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el c贸digo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python en el servidor
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar las librer铆as necesarias
        run: |
          pip install requests beautifulsoup4 python-docx

      - name: Ejecutar el buscador
        run: python buscador.py

      - name: Guardar el Word generado como copia de seguridad
        uses: actions/upload-artifact@v4
        with:
          name: Informe-Oposiciones
          path: "*.docx"

      - name: Enviar Informe por Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 465 # Cambiado de 587 a 465
          secure: true     # Obligamos a usar conexi贸n segura desde el inicio
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: " Oposiciones TIC - Reporte"
          to: ${{ secrets.EMAIL_USER }}
          from: "Buscador Autom谩tico"
          body: "Informe generado por el robot de GitHub."
          attachments: "*.docx"
