name: Buscador Diario Oposiciones

on:
  schedule:
    - cron: '0 8 * * *'  # Esto se ejecuta a las 8:00 AM todos los d칤as
  workflow_dispatch:      # Esto te permite darle a un bot칩n y ejecutarlo cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el c칩digo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python en el servidor
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar las librer칤as necesarias
        run: |
          pip install requests beautifulsoup4 python-docx

      - name: Ejecutar el buscador
        run: python buscador.py

      - name: Guardar el Word generado como resultado
        uses: actions/upload-artifact@v4
        with:
          name: Informe-Oposiciones
          path: "*.docx"
      - name: Enviar Informe por Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "游늭 Oposiciones TIC - 15 d칤as"
          to: ${{ secrets.EMAIL_USER }}
          from: "Buscador Autom치tico"
          body: "Se adjunta el informe de oposiciones generado hoy autom치ticamente por GitHub."
          attachments: "*.docx"
