name: Buscador Diario Oposiciones

on:
  schedule:
    - cron: '0 8 * * *'  # Se ejecuta a las 8:00 AM cada d칤a
  workflow_dispatch:      # Permite ejecuci칩n manual con el bot칩n "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el c칩digo del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python en el servidor
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar las librer칤as necesarias
        run: |
          pip install requests beautifulsoup4 python-docx

      - name: Ejecutar el buscador
        run: python buscador.py

      - name: Guardar el Word generado como copia de seguridad
        uses: actions/upload-artifact@v4
        with:
          name: Informe-Oposiciones
          path: "*.docx"

      - name: Enviar Informe por Email (GMAIL)
        if: always()  # Se ejecuta incluso si no hay plazas nuevas, para confirmar que funciona
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "游늭 Reporte de Oposiciones TIC - 15 d칤as"
          to: ${{ secrets.EMAIL_USER }}
          from: "Buscador Autom치tico"
          body: "Hola, se adjunta el informe con las oposiciones encontradas hoy por el robot."
          attachments: "*.docx"
